services:
  - type: web
    name: coffee-rating-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/coffees
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
